spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpachan
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #none으로 하면 테이블드랍을 안하고 반복해서 데이터베이스의 데이터를 쓸 수 있다.
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
